{
 "title": "MongoDB Monitoring Dashboard 2021.10.1",
 "description": "MongoDB basic dashboard for health & monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Pods & Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB Instance Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds",
     "legendFormat": "Uptime Second"
    }
   ]
  },
  {
   "title": "CPU % User",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_sys_cpu_user_ms / (mongodb_sys_cpu_user_ms + mongodb_sys_cpu_idle_ms) * 100",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "CPU % Idle",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_sys_cpu_idle_ms/ (mongodb_sys_cpu_user_ms + mongodb_sys_cpu_idle_ms) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU User vs Idle: Time Series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg (rate(mongodb_sys_cpu_user_ms[5m]) or irate(mongodb_sys_cpu_user_ms[5m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg (rate(mongodb_sys_cpu_idle_ms[5m]) or irate(mongodb_sys_cpu_idle_ms[5m]))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Pod Stats",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"mongodb\", pod=~\"mongodb-replica-set.*\"})",
     "legendFormat": "Replica-Set(s)"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"mongodb\", pod=~\"mongodb-replica-set.*\", container=\"mongod\"}",
     "legendFormat": "MongoD Restarts"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"mongodb\", pod=~\"mongodb-replica-set.*\", container=\"mongodb-agent\"}",
     "legendFormat": "Agent Restarts"
    }
   ]
  },
  {
   "title": "Pod CPU Utilization: MongoD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"mongodb\", pod=~\"mongodb-replica.*\", container=\"mongod\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"mongodb\", pod=~\"mongodb-replica.*\", container=\"mongod\", resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"mongodb\", pod=~\"mongodb-replica.*\", container=\"mongod\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Pod Memory Utilization: MongoD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"mongodb\", pod=~\"mongodb-replica.*\", container=\"mongod\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"mongodb\", pod=~\"mongodb-replica.*\", container=\"mongod\", resource=\"memory\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"mongodb\", pod=~\"mongodb-replica.*\", container=\"mongod\", resource=\"memory\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Replica Set Disk IOPS (Reads + Writes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{pod=~\"mongodb-replica-.*\", namespace=\"mongodb\"}[5m]) + rate(container_fs_writes_total{pod=~\"mongodb-replica-.*\", namespace=\"mongodb\"}[5m])))",
     "legendFormat": "fs read / write"
    }
   ]
  },
  {
   "title": "Steady State Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "mongodb_ss_mem_resident", "legendFormat": "Resident" },
    { "expr": "mongodb_ss_mem_virtual", "legendFormat": "Virtual" }
   ]
  },
  {
   "title": "Op Execution Time (Latency)",
   "type": "timeseries",
   "description": "Average latency of operations (classified by read or write command)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg (rate(mongodb_mongod_op_latencies_latency_total{type=~\"read\"}[5m]) / (rate(mongodb_mongod_op_latencies_ops_total{type=~\"read\"}[5m]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{type=~\"read\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{type=~\"read\"}[5m]) > 0))",
     "legendFormat": "Read"
    },
    {
     "expr": "avg (rate(mongodb_mongod_op_latencies_latency_total{type=~\"write\"}[5m]) / (rate(mongodb_mongod_op_latencies_ops_total{type=~\"write\"}[5m]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{type=~\"write\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{type=~\"write\"}[5m]) > 0))",
     "legendFormat": "Write"
    },
    {
     "expr": "avg (rate(mongodb_mongod_op_latencies_latency_total{type=\"command\"}[5m]) / (rate(mongodb_mongod_op_latencies_ops_total{type=\"command\"}[5m]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{type=\"command\"}[5m]) > 0))",
     "legendFormat": "Command"
    }
   ]
  },
  {
   "title": "OpCounters",
   "type": "timeseries",
   "description": "Ops/sec, classified by legacy wire protocol type (query, insert, update, delete, getmore).",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(mongodb_op_counters_total{type!=\"command\"}[5m]) or \r\nirate(mongodb_op_counters_total{type!=\"command\"}[5m]))",
     "legendFormat": "MongoDB OpCounters Total"
    }
   ]
  },
  {
   "title": "Query Planner Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg (rate(mongodb_mongod_metrics_query_executor_total{state=\"scanned_objects\"}[5m]) or \nirate(mongodb_mongod_metrics_query_executor_total{state=\"scanned_objects\"}[5m]))",
     "legendFormat": "Scanned Objects / sec"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag"
    }
   ]
  },
  { "title": "MongoDB Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Replica Set: Network Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"mongodb\", pod=\"mongodb-replica-set-0\"}[5m]))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"mongodb\", pod=\"mongodb-replica-set-0\"}[5m]))",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "MongoDB Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_connections{state=\"current\"}[5m]) or \nmax_over_time(mongodb_mongos_connections{state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{state=\"current\"}[5m]))",
     "legendFormat": "Current"
    },
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_connections{state=\"active\"}[5m]) or \nmax_over_time(mongodb_mongos_connections{state=\"active\"}[5m]) or\nmax_over_time(mongodb_connections{state=\"active\"}[5m]))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "MongoDB Exporter: Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"mongodb\", pod=~\"mongodb-exporter.*\"}[5m]))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"mongodb\", pod=~\"mongodb-exporter.*\"}[5m]))",
     "legendFormat": "Send"
    }
   ]
  },
  { "title": "Data Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Data: % Volume Available",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"data-volume-mongodb-replica-set-0\"})\n/\n\r\nsum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"data-volume-mongodb-replica-set-0\"})\r\n) * 100"
    }
   ]
  },
  {
   "title": "Logs: % Volume Available",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"logs-volume-mongodb-replica-set-0\"})\n/\n\r\nsum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"logs-volume-mongodb-replica-set-0\"})\r\n) * 100"
    }
   ]
  },
  {
   "title": "Persistent Volumes: Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(\r\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"data-volume-mongodb-replica-set-0\"})\r\n  -\r\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"data-volume-mongodb-replica-set-0\"})\r\n)",
     "legendFormat": "Data: Used Space"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"data-volume-mongodb-replica-set-0\"})",
     "legendFormat": "Data: Free Space"
    }
   ]
  },
  {
   "title": "Persistent Volumes: Logs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(\r\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"logs-volume-mongodb-replica-set-0\"})\r\n  -\r\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"logs-volume-mongodb-replica-set-0\"})\r\n)",
     "legendFormat": "Logs: Used Space"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"logs-volume-mongodb-replica-set-0\"})",
     "legendFormat": "Logs: Free Space"
    }
   ]
  },
  {
   "title": "Total Volume Capacity: Data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"data-volume-mongodb-replica-set-0\"})",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "title": "Total Volume Capacity: Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"mongodb\", persistentvolumeclaim=\"logs-volume-mongodb-replica-set-0\"})",
     "legendFormat": "Logs"
    }
   ]
  },
  { "title": "Apps Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU : apps-server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"uipath\", container!=\"istio-proxy\", pod=~\"apps-server.*\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"uipath\", pod=~\"apps-server.*\", container!=\"istio-proxy\", resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"uipath\", pod=~\"apps-server.*\", container!=\"istio-proxy\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory : apps-server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"uipath\", pod=~\"apps-server.*\",container!=\"istio-proxy\", image!=\"\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"uipath\", pod=~\"apps-server.*\", container!=\"istio-proxy\", resource=\"memory\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"uipath\", pod=~\"apps-server.*\", container!=\"istio-proxy\", resource=\"memory\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Network : Apps Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"uipath\", pod=~\"apps-server.*\"}[5m]))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"uipath\", pod=~\"apps-server.*\"}[5m]))",
     "legendFormat": "Send"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 } }
 ]
}